name: Backend_unit_tests

on:
  workflow_dispatch:
  pull_request:
    types: [review_requested]
    branches: [ dev, deploy ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '3.1.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: Backend/VaccinationSystem
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Backend/VaccinationSystem
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: Backend/VaccinationSystem
